# Generated by Django 3.2.8 on 2021-11-14 00:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0004_followers'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Followers',
        ),
    ]
