# Generated by Django 3.2.8 on 2021-11-14 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0006_suscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='spotifyLink',
            field=models.URLField(blank=True),
        ),
    ]
