# Generated by Django 3.2.8 on 2021-11-15 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0007_post_spotifylink'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='embedSpotifyLink',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
